#!/usr/bin/env -S ./lua

local in_path = arg[1] or "locale/native/native.lua"
local out_path = arg[2] or "locale/native/native_kernel_autogenerated.h"

local locale = dofile(in_path)
if locale == nil and type(_G.locale) == "table" then
  locale = _G.locale
  _G.locale = nil
end
assert(type(locale) == "table", "locale chunk did not provide a table")

local keyword_keys = {
  "conjunction·operator",
  "iteration·escape",
  "block·introducer",
  "conditional·alternative",
  "conditional·alternative·protasis",
  "block·terminator",
  "falsity·literal",
  "iteration·introducer",
  "function·introducer",
  "dynamic·scope·declaration",
  "unconditional·transfer",
  "conditional·protasis",
  "iteration·domain",
  "lexical·scope·declaration",
  "null·literal",
  "negation·operator",
  "disjunction·operator",
  "postcondition·iteration·introducer",
  "result·emission",
  "conditional·apodosis",
  "truth·literal",
  "postcondition·iteration·terminator",
  "precondition·iteration·introducer",
}

local operator_keys = {
  "integer·division·operator",
  "concatenation·operator",
  "variadic·expansion",
  "equality·comparison",
  "superior·ordering·comparison",
  "inferior·ordering·comparison",
  "inequality·comparison",
  "ascending·significance·shift",
  "descending·significance·shift",
  "label·delimiter",
}

local lexical_keys = {
  "eof·token",
  "number·token",
  "integer·token",
  "name·token",
  "string·token",
}

local delimiters = {
  { "expression·grouping·opening", "(" },
  { "expression·grouping·closing", ")" },
  { "index·opening", "[" },
  { "index·closing", "]" },
  { "constructor·opening", "{" },
  { "constructor·closing", "}" },
  { "element·separator", "," },
  { "statement·separator", ";" },
  { "string·delimiter", "\"" },
  { "string·delimiter·alternate", "'" },
}

local function c_quote(s)
  return "\"" ..
    s:gsub("\\", "\\\\")
     :gsub("\"", "\\\"")
     :gsub("\n", "\\n")
     :gsub("\r", "\\r")
     :gsub("\t", "\\t") ..
    "\""
end

local function get(tbl, key)
  local v = tbl[key]
  assert(type(v) == "string", "missing string key: " .. tostring(key))
  return v
end

local function emit_array(out, macro, values)
  out:write("#define ", macro, " \\\n")
  out:write("  { \\\n")
  for i, v in ipairs(values) do
    local sep = (i < #values) and "," or ""
    out:write("    ", c_quote(v), sep, " \\\n")
  end
  out:write("  }\n\n")
end

local bootstrap_tokens = {}
for _, k in ipairs(keyword_keys) do
  bootstrap_tokens[#bootstrap_tokens + 1] = get(locale.keywords, k)
end
for _, k in ipairs(operator_keys) do
  bootstrap_tokens[#bootstrap_tokens + 1] = get(locale.operators, k)
end
for _, k in ipairs(lexical_keys) do
  bootstrap_tokens[#bootstrap_tokens + 1] = get(locale.lexical, k)
end

local out = assert(io.open(out_path, "w"))

out:write([[
/*
** AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
** Generated by utilitary/generate-native-locale-kernel-header.lua
** Source: ]], in_path, [[
*/

#ifndef ]])

local guard = out_path:match("([^/]+)%.h$")
guard = (guard or "kernel_locale_autogenerated"):gsub("[^%w]", "_")

out:write(guard, [[_h
#define ]], guard, [[_h

]])

emit_array(out, "LUA_KERNEL_BOOTSTRAP_TOKENS", bootstrap_tokens)
emit_array(out, "LUA_KERNEL_KEYWORD_KEYS", keyword_keys)
emit_array(out, "LUA_KERNEL_OPERATOR_KEYS", operator_keys)
emit_array(out, "LUA_KERNEL_LEXICAL_KEYS", lexical_keys)

for _, d in ipairs(delimiters) do
  local keyname = d[1]:upper()
    :gsub("·", "_")
    :gsub("[^A-Z0-9_]", "_")
  out:write("#define LUA_KERNEL_DELIM_KEY_", keyname, " ", c_quote(d[1]), "\n")
  out:write("#define LUA_KERNEL_DELIM_DEFAULT_", keyname, " ", c_quote(d[2]), "\n")
end

out:write("\n#endif\n")
out:close()
