# Developer's makefile for building Lua
# see luaconf.h for further customization

# == CHANGE THE SETTINGS BELOW TO SUIT YOUR ENVIRONMENT =======================

UNAME_S := $(shell uname -s)

# Warnings valid for both C and C++
CWARNSCPP= \
	-Wfatal-errors \
	-Wextra \
	-Wshadow \
	-Wundef \
	-Wwrite-strings \
	-Wredundant-decls \
	-Wdisabled-optimization \
	-Wdouble-promotion \
	-Wmissing-declarations \
        # the next warnings might be useful sometimes,
	# but usually they generate too much noise
	# -Wstrict-overflow=2 \
	# -Werror \
	# -pedantic   # warns if we use jump tables \
	# -Wformat=2 \
	# -Wcast-qual \


# Warnings for gcc, not valid for clang
ifeq ($(UNAME_S),Darwin)
CWARNGCC=
else
CWARNGCC= \
	-Wlogical-op \
	-Wno-aggressive-loop-optimizations
endif


# The next warnings are neither valid nor needed for C++
ifeq ($(UNAME_S),Darwin)
CWARNCONV=
CWARNSC= -Wmissing-prototypes \
	-Wnested-externs \
	-Wstrict-prototypes \
	-Wc++-compat \
	-Wold-style-definition
else
CWARNCONV= -Wconversion
CWARNSC= -Wdeclaration-after-statement \
	-Wmissing-prototypes \
	-Wnested-externs \
	-Wstrict-prototypes \
	-Wc++-compat \
	-Wold-style-definition
endif


CWARNS= $(CWARNSCPP) $(CWARNSC) $(CWARNCONV) $(CWARNGCC)

# Some useful compiler options for internal tests:
# -DLUAI_ASSERT turns on all assertions inside Lua.
# -DHARDSTACKTESTS forces a reallocation of the stack at every point where
# the stack can be reallocated.
# -DHARDMEMTESTS forces a full collection at all points where the collector
# can run.
# -DEMERGENCYGCTESTS forces an emergency collection at every single allocation.
# -DEXTERNMEMCHECK removes internal consistency checking of blocks being
# deallocated (useful when an external tool like valgrind does the check).
# -DMAXINDEXRK=k limits range of constants in RK instruction operands.
# -DLUA_COMPAT_5_3

# -pg -malign-double
# -DLUA_USE_CTYPE -DLUA_USE_APICHECK

# The following options help detect "undefined behavior"s that seldom
# create problems; some are only available in newer gcc versions. To
# use some of them, we also have to define an environment variable
# ASAN_OPTIONS="detect_invalid_pointer_pairs=2".
# -fsanitize=undefined  (you may need to add "-lubsan" to libs)
# -fsanitize=pointer-subtract -fsanitize=address -fsanitize=pointer-compare

# Test mode: Add test library, turn on asserts, redefine several
# constants ("to give some bugs a chance"), track memory use, and add
# debug information.
# TESTS= -DLUA_USER_H='"ltests.h"' -Og -g

LOCAL = $(TESTS) $(CWARNS)


# To enable Linux goodies, -DLUA_USE_LINUX
# For C89, "-std=c89 -DLUA_USE_C89"
# Note that Linux/Posix options are not compatible with C89
# (For 32-bit, add option "-m32" to MYCFLAGS and MYLDFLAGS.)
ifeq ($(UNAME_S),Darwin)
READLINE_DYLIB := /opt/homebrew/opt/readline/lib/libreadline.dylib
MYCFLAGS ?= $(LOCAL) -std=c99 -DLUA_USE_POSIX -DLUA_USE_DLOPEN -DLUA_READLINELIB="\"$(READLINE_DYLIB)\""
MYLDFLAGS ?=
MYLIBS ?=
CC ?= cc
else
MYCFLAGS ?= $(LOCAL) -std=c99 -DLUA_USE_LINUX
MYLDFLAGS ?= -Wl,-E
MYLIBS ?= -ldl
CC ?= gcc
endif
LUA_KERNEL_LOCALE= native
LUA_KERNEL_LOCALE_DIR= locale/$(LUA_KERNEL_LOCALE)
LUA_KERNEL_LOCALE_FILE= $(LUA_KERNEL_LOCALE_DIR)/$(LUA_KERNEL_LOCALE).lua
LUA_KERNEL_LOCALE_HEADER= $(LUA_KERNEL_LOCALE_DIR)/$(LUA_KERNEL_LOCALE)_kernel_autogenerated.h


# (Optionally we can use -march=native -mno-avx512f.)
CFLAGS= -Wall -O2 $(MYCFLAGS) -DLUA_DEFAULT_LOCALE=\"$(LUA_KERNEL_LOCALE)\" \
	-DLUA_BASE_LOCALE=\"$(LUA_KERNEL_LOCALE)\" \
	-DLUA_KERNEL_LOCALE_HEADER=\"$(LUA_KERNEL_LOCALE_HEADER)\" \
	-fno-stack-protector -fno-common
AR= ar rc
RANLIB= ranlib
RM= rm -f



# == END OF USER SETTINGS. NO NEED TO CHANGE ANYTHING BELOW THIS LINE =========


LIBS = -lm

CORE_T=	liblua.a
CORE_O=	lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o \
	lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o \
	ltm.o lundump.o lvm.o lzio.o ltests.o utf8proc/utf8proc.o
AUX_O=	lauxlib.o
LIB_O=	lbaselib.o ldblib.o liolib.o lmathlib.o loslib.o ltablib.o lstrlib.o \
	lutf8lib.o loadlib.o lcorolib.o linit.o

LUA_T=	lua
LUA_O=	lua.o


ALL_T= $(CORE_T) $(LUA_T)
ALL_O= $(CORE_O) $(LUA_O) $(AUX_O) $(LIB_O)
ALL_A= $(CORE_T)
KERNEL_LOCALE_STAMP= .last-kernel-locale

.PHONY: ensure-kernel-locale
all: ensure-kernel-locale $(ALL_T)
	touch all

ensure-kernel-locale:
	@if [ -f "$(KERNEL_LOCALE_STAMP)" ] && \
		[ "$$(cat "$(KERNEL_LOCALE_STAMP)")" != "$(LUA_KERNEL_LOCALE)" ]; then \
		echo "kernel locale changed: $$(cat "$(KERNEL_LOCALE_STAMP)") -> $(LUA_KERNEL_LOCALE); cleaning"; \
		$(MAKE) clean; \
	fi
	@printf "%s\n" "$(LUA_KERNEL_LOCALE)" > "$(KERNEL_LOCALE_STAMP)"

$(LUA_KERNEL_LOCALE_HEADER): $(LUA_KERNEL_LOCALE_FILE) utilitary/generate-native-locale-kernel-header.lua
	@if command -v lua >/dev/null 2>&1; then \
		lua utilitary/generate-native-locale-kernel-header.lua \
			$(LUA_KERNEL_LOCALE_FILE) $(LUA_KERNEL_LOCALE_HEADER); \
	elif command -v luajit >/dev/null 2>&1; then \
		luajit utilitary/generate-native-locale-kernel-header.lua \
			$(LUA_KERNEL_LOCALE_FILE) $(LUA_KERNEL_LOCALE_HEADER); \
	elif [ -x ./$(LUA_T) ]; then \
		./$(LUA_T) utilitary/generate-native-locale-kernel-header.lua \
			$(LUA_KERNEL_LOCALE_FILE) $(LUA_KERNEL_LOCALE_HEADER); \
	else \
		echo "error: no Lua interpreter available for header regeneration"; \
		exit 1; \
	fi

regen-kernel-header: $(LUA_KERNEL_LOCALE_HEADER)

regen-native-kernel-header: regen-kernel-header

LOCALE_BUILD_PREREQS= ensure-kernel-locale regen-kernel-header all

locale-build: $(LOCALE_BUILD_PREREQS)

LOCALE_NAMES := $(notdir $(wildcard locale/*))

.PHONY: $(LOCALE_NAMES)
$(LOCALE_NAMES):
	@$(MAKE) locale-build LUA_KERNEL_LOCALE="$@"

o:	$(ALL_O)

a:	$(ALL_A)

$(CORE_T): $(CORE_O) $(AUX_O) $(LIB_O)
	$(AR) $@ $?
	$(RANLIB) $@

$(LUA_T): $(LUA_O) $(CORE_T)
	$(CC) -o $@ $(MYLDFLAGS) $(LUA_O) $(CORE_T) $(LIBS) $(MYLIBS) $(DL)


clean:
	$(RM) $(ALL_T) $(ALL_O)

depend:
	@$(CC) $(CFLAGS) -MM *.c

echo:
	@echo "CC = $(CC)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "AR = $(AR)"
	@echo "RANLIB = $(RANLIB)"
	@echo "RM = $(RM)"
	@echo "MYCFLAGS = $(MYCFLAGS)"
	@echo "MYLDFLAGS = $(MYLDFLAGS)"
	@echo "MYLIBS = $(MYLIBS)"
	@echo "LUA_KERNEL_LOCALE = $(LUA_KERNEL_LOCALE)"
	@echo "LUA_KERNEL_LOCALE_FILE = $(LUA_KERNEL_LOCALE_FILE)"
	@echo "LUA_KERNEL_LOCALE_HEADER = $(LUA_KERNEL_LOCALE_HEADER)"
	@echo "LUA_KERNEL_LOCALE_INCLUDE = $(LUA_KERNEL_LOCALE_INCLUDE)"
	@echo "DL = $(DL)"

$(ALL_O): makefile ltests.h

# DO NOT EDIT
# automatically made with 'gcc -MM l*.c'

lapi.o: lapi.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h ldebug.h ldo.h lfunc.h lgc.h lstring.h \
 ltable.h lundump.h lvm.h
lauxlib.o: lauxlib.c lprefix.h lua.h luaconf.h lauxlib.h llimits.h
lbaselib.o: lbaselib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
lcode.o: lcode.c lprefix.h lua.h luaconf.h lcode.h llex.h lobject.h \
 llimits.h lzio.h lmem.h lopcodes.h lparser.h ldebug.h lstate.h ltm.h \
 ldo.h lgc.h lstring.h ltable.h lvm.h lopnames.h
lcorolib.o: lcorolib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
lctype.o: lctype.c lprefix.h lctype.h lua.h luaconf.h llimits.h
ldblib.o: ldblib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h llimits.h
ldebug.o: ldebug.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h lcode.h llex.h lopcodes.h lparser.h \
 ldebug.h ldo.h lfunc.h lstring.h lgc.h ltable.h lvm.h
ldo.o: ldo.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h ldebug.h ldo.h lfunc.h lgc.h lopcodes.h \
 lparser.h lstring.h ltable.h lundump.h lvm.h
ldump.o: ldump.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h lgc.h ltable.h lundump.h
lfunc.o: lfunc.c lprefix.h lua.h luaconf.h ldebug.h lstate.h lobject.h \
 llimits.h ltm.h lzio.h lmem.h ldo.h lfunc.h lgc.h
lgc.o: lgc.c lprefix.h lua.h luaconf.h ldebug.h lstate.h lobject.h \
 llimits.h ltm.h lzio.h lmem.h ldo.h lfunc.h lgc.h lstring.h ltable.h
linit.o: linit.c lprefix.h lua.h luaconf.h lualib.h lauxlib.h llimits.h
liolib.o: liolib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h llimits.h
llex.o: llex.c lprefix.h lua.h luaconf.h lctype.h llimits.h ldebug.h \
 lstate.h lobject.h ltm.h lzio.h lmem.h ldo.h lgc.h llex.h lparser.h \
 lstring.h ltable.h $(LUA_KERNEL_LOCALE_HEADER)
lmathlib.o: lmathlib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
lmem.o: lmem.c lprefix.h lua.h luaconf.h ldebug.h lstate.h lobject.h \
 llimits.h ltm.h lzio.h lmem.h ldo.h lgc.h
loadlib.o: loadlib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
lobject.o: lobject.c lprefix.h lua.h luaconf.h lctype.h llimits.h \
 ldebug.h lstate.h lobject.h ltm.h lzio.h lmem.h ldo.h lstring.h lgc.h \
 lvm.h
lopcodes.o: lopcodes.c lprefix.h lopcodes.h llimits.h lua.h luaconf.h \
 lobject.h
loslib.o: loslib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h llimits.h
lparser.o: lparser.c lprefix.h lua.h luaconf.h lcode.h llex.h lobject.h \
 llimits.h lzio.h lmem.h lopcodes.h lparser.h ldebug.h lstate.h ltm.h \
 ldo.h lfunc.h lstring.h lgc.h ltable.h
lstate.o: lstate.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h ldebug.h ldo.h lfunc.h lgc.h llex.h \
 lstring.h ltable.h
lstring.o: lstring.c lprefix.h lua.h luaconf.h ldebug.h lstate.h \
 lobject.h llimits.h ltm.h lzio.h lmem.h ldo.h lstring.h lgc.h
lstrlib.o: lstrlib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
ltable.o: ltable.c lprefix.h lua.h luaconf.h ldebug.h lstate.h lobject.h \
 llimits.h ltm.h lzio.h lmem.h ldo.h lgc.h lstring.h ltable.h lvm.h
ltablib.o: ltablib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
ltests.o: ltests.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h lauxlib.h lcode.h llex.h lopcodes.h \
 lparser.h lctype.h ldebug.h ldo.h lfunc.h lopnames.h lstring.h lgc.h \
 ltable.h lualib.h
ltm.o: ltm.c lprefix.h lua.h luaconf.h ldebug.h lstate.h lobject.h \
 llimits.h ltm.h lzio.h lmem.h ldo.h lgc.h lstring.h ltable.h lvm.h
lua.o: lua.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h llimits.h
lundump.o: lundump.c lprefix.h lua.h luaconf.h ldebug.h lstate.h \
 lobject.h llimits.h ltm.h lzio.h lmem.h ldo.h lfunc.h lstring.h lgc.h \
 ltable.h lundump.h
lutf8lib.o: lutf8lib.c lprefix.h lua.h luaconf.h lauxlib.h lualib.h \
 llimits.h
lvm.o: lvm.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h ldebug.h ldo.h lfunc.h lgc.h lopcodes.h \
 lstring.h ltable.h lvm.h ljumptab.h
lzio.o: lzio.c lprefix.h lua.h luaconf.h lapi.h llimits.h lstate.h \
 lobject.h ltm.h lzio.h lmem.h

# (end of Makefile)
