/*
** AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
** Generated by utilitary/generate-native-locale-kernel-header.lua
** Source: locale/native.lua
*/

#ifndef native_locale_kernel_autogenerated_h
#define native_locale_kernel_autogenerated_h

#define LUA_KERNEL_BOOTSTRAP_TOKENS \
  { \
    "and", \
    "break", \
    "do", \
    "else", \
    "elseif", \
    "end", \
    "false", \
    "for", \
    "function", \
    "global", \
    "goto", \
    "if", \
    "in", \
    "local", \
    "nil", \
    "not", \
    "or", \
    "repeat", \
    "return", \
    "then", \
    "true", \
    "until", \
    "while", \
    "//", \
    "..", \
    "...", \
    "==", \
    ">=", \
    "<=", \
    "~=", \
    "<<", \
    ">>", \
    "::", \
    "<eof>", \
    "<number>", \
    "<integer>", \
    "<name>", \
    "<string>" \
  }

#define LUA_KERNEL_KEYWORD_KEYS \
  { \
    "conjunction·operator", \
    "iteration·escape", \
    "block·introducer", \
    "conditional·alternative", \
    "conditional·alternative·protasis", \
    "block·terminator", \
    "falsity·literal", \
    "iteration·introducer", \
    "function·introducer", \
    "dynamic·scope·declaration", \
    "unconditional·transfer", \
    "conditional·protasis", \
    "iteration·domain", \
    "lexical·scope·declaration", \
    "null·literal", \
    "negation·operator", \
    "disjunction·operator", \
    "postcondition·iteration·introducer", \
    "result·emission", \
    "conditional·apodosis", \
    "truth·literal", \
    "postcondition·iteration·terminator", \
    "precondition·iteration·introducer" \
  }

#define LUA_KERNEL_OPERATOR_KEYS \
  { \
    "integer·division·operator", \
    "concatenation·operator", \
    "variadic·expansion", \
    "equality·comparison", \
    "superior·ordering·comparison", \
    "inferior·ordering·comparison", \
    "inequality·comparison", \
    "ascending·significance·shift", \
    "descending·significance·shift", \
    "label·delimiter" \
  }

#define LUA_KERNEL_LEXICAL_KEYS \
  { \
    "eof·token", \
    "number·token", \
    "integer·token", \
    "name·token", \
    "string·token" \
  }

#define LUA_KERNEL_DELIM_KEY_EXPRESSION_GROUPING_OPENING "expression·grouping·opening"
#define LUA_KERNEL_DELIM_DEFAULT_EXPRESSION_GROUPING_OPENING "("
#define LUA_KERNEL_DELIM_KEY_EXPRESSION_GROUPING_CLOSING "expression·grouping·closing"
#define LUA_KERNEL_DELIM_DEFAULT_EXPRESSION_GROUPING_CLOSING ")"
#define LUA_KERNEL_DELIM_KEY_INDEX_OPENING "index·opening"
#define LUA_KERNEL_DELIM_DEFAULT_INDEX_OPENING "["
#define LUA_KERNEL_DELIM_KEY_INDEX_CLOSING "index·closing"
#define LUA_KERNEL_DELIM_DEFAULT_INDEX_CLOSING "]"
#define LUA_KERNEL_DELIM_KEY_CONSTRUCTOR_OPENING "constructor·opening"
#define LUA_KERNEL_DELIM_DEFAULT_CONSTRUCTOR_OPENING "{"
#define LUA_KERNEL_DELIM_KEY_CONSTRUCTOR_CLOSING "constructor·closing"
#define LUA_KERNEL_DELIM_DEFAULT_CONSTRUCTOR_CLOSING "}"
#define LUA_KERNEL_DELIM_KEY_ELEMENT_SEPARATOR "element·separator"
#define LUA_KERNEL_DELIM_DEFAULT_ELEMENT_SEPARATOR ","
#define LUA_KERNEL_DELIM_KEY_STATEMENT_SEPARATOR "statement·separator"
#define LUA_KERNEL_DELIM_DEFAULT_STATEMENT_SEPARATOR ";"
#define LUA_KERNEL_DELIM_KEY_STRING_DELIMITER "string·delimiter"
#define LUA_KERNEL_DELIM_DEFAULT_STRING_DELIMITER "\""
#define LUA_KERNEL_DELIM_KEY_STRING_DELIMITER_ALTERNATE "string·delimiter·alternate"
#define LUA_KERNEL_DELIM_DEFAULT_STRING_DELIMITER_ALTERNATE "'"

#endif
